[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
included_files = [
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/router-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
]

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image*"
  status = 200
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/redirects/mml-starter-project-codesandbox"
  to = "https://codesandbox.io/p/sandbox/stoic-fire-tlx9k6"
  status = 302

[[redirects]]
  from = "/redirects/mml-playground-codesandbox"
  to = "https://codesandbox.io/p/sandbox/df546f"
  status = 302

[[plugins]]
  package = "@netlify/plugin-nextjs"

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
